---
title: "numeric_eda"
output: github_document
date: "2022-10-03"
---

```{r}
library(tidyverse)

```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% #create month column, lubridate helps with date/time data, floor_date round date to the 1st of the month
  select(name, id, everything())
```

## `group_by()`

```{r}
weather_df %>%
  group_by(name, month) #creates 36 groups
```

## `summarize()`

let's group and then summarize!

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n() #count number of rows of each group, result is a tibble, create new var n_obs
  )
```

can we count in other ways?

```{r}
weather_df %>%
  count(name, month)
```

don't use `table()`

you can have multiple summaries
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_dist = n_distinct(month) #count number of unique things
  )
```

## a brief aside on 2x2 table
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>%
  group_by(name, cold) %>%
  summarize(
    n_obs = n()
  ) %>%
  pivot_wider(
    names_from = cold,
    values_from = n_obs 
  )
```

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>%
  janitor::tabyl(name, cold)
```

## General Summaries

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE), #remove na prior to compute the mean
    sd_prcp = sd(prcp),
    median_tmax = median(tmax, na.rm = TRUE)
  )
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(prcp:tmin, mean)) #compute mean from var prcp to tmin
```


This is a dataframe!!!

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  ggplot(aes( x = month, y = mean_tmax, color = name)) + 
  geom_point() + 
  geom_path()
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>%
  knitr::kable(digit = 2) #not produce df, but a nicer looking table
```


## Grouped mutates

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>%
  ggplot(aes(x = date, y = centered_tmax, color = name)) + geom_point()
View(weather_df)
```


lagged observation
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    yesterday_tmax = lag(tmax),
    tmax_change = tmax - yesterday_tmax
  ) %>%
  summarize(
    sd_tmax_change = sd(tmax_change, na.rm = TRUE)
  )
```

One other window function..

```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(
    tmax_rank = min_rank(tmax)
  ) %>%
  filter(tmax_rank < 4) %>%
  arrange(name, month, tmax_rank)
```

