---
title: "vis_p2"
output: github_document
date: "2022-10-03"
---

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatter plot

But better this time

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    x = "Minimum Daily Temp(C)",
    y = "Maximum Daily Temp(C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package"
  ) + #labs adds captions
  scale_x_continuous(
    breaks = c(-10, 0, 15),
    labels = c("10C", "0", "15")
  ) + #can change scale
  scale_y_continuous(
    trans = "sqrt"
  )
```

make a new version
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    x = "Minimum Daily Temp(C)",
    y = "Maximum Daily Temp(C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package"
  ) +
  scale_color_hue(
    name = "Location", #change legend title
    h = c(100,300)
    ) #change color
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    x = "Minimum Daily Temp(C)",
    y = "Maximum Daily Temp(C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package"
  ) +
  viridis::scale_color_viridis( #color palatte
    name = "Location",
    discrete = TRUE
  )
```

## Themes

```{r}
gg_weather = weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    x = "Minimum Daily Temp(C)",
    y = "Maximum Daily Temp(C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package"
  ) +
  viridis::scale_color_viridis( #color palatte
    name = "Location",
    discrete = TRUE
  )
```

```{r}
gg_weather +
  theme(legend.position = "bottom") + #change legend position
  theme_bw() #black and white theme, there are also theme_minimal(), theme_classic()
```

# Data in geom()

```{r}
central_park_df = 
  weather_df %>%
  filter(name == "CentralPark_NY")

waikiki_df = 
  weather_df %>%
  filter(name == "Waikiki_HA")

ggplot(waikiki_df, aes(x = date, y = tmax)) +
  geom_point() +
  geom_line(data = central_park_df)
```

## Patchwork

```{r}
tmax_tmin_plot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")

prcp_density_plot = 
  weather_df %>%
  filter(prcp > 0) %>%
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5) + 
  theme(legend.position = "none")

seasonality_plot = 
  weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")

tmax_tmin_plot + prcp_density_plot #patchwork put 2 figures side by side (dont use facet because not similar plot)

(tmax_tmin_plot + prcp_density_plot) / seasonality_plot
```

## Data manipulation

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

x-axis have to be factor variable, r use alphabetical order to convert char to factor. 

```{r}
weather_df %>%
  mutate(name = fct_relevel(name, "Waikiki_HA")) %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
#put Waikiki first by factor relevel
```

```{r}
weather_df %>%
  mutate(name = fct_reorder(name, tmax)) %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
#reorder factor by tmax
```

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything())  %>%
  mutate(
    visit = fct_relevel(visit, "bl")
  )

pulse_data %>%
  ggplot(aes(x = visit, y = bdi)) + 
  geom_boxplot()
```

